routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::middleware('auth')->group(function () {
    Route::get('/tweets', 'TweetsController@index')->name('home');
    Route::post('/tweets', 'TweetsController@store');

    Route::post('/profiles/{user}/follow', 'FollowsController@store');
    Route::get('/profiles/{user}/edit', 'ProfilesController@edit');
});

Route::get('/profiles/{user}', 'ProfilesController@show')->name('profile');



Auth::routes();

app/Followable.php
<?php


namespace App;


trait Followable
{
    public function follow(User $user)
    {
        return $this->follows()->save($user);
    }

    public function unfollow(User $user)
    {
        return $this->follows()->detach($user);
    }

    public function toggleFollow(User $user)
    {
        if ($this->following($user)) {
            return $this->unfollow($user);
        }
        return $this->follow($user);
    }

    public function following(User $user)
    {
        return $this->follows()
            ->where('following_user_id', $user->id)
            ->exists();
    }

    public function follows()
    {
        return $this->belongsToMany(User::class, 'follows', 'user_id', 'following_user_id');
    }
}

app/Tweet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tweet extends Model
{
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, Followable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarAttribute()
    {
        return "https://api.adorable.io/avatars/150/" . $this->email;
    }

    public function timeline()
    {
        $friends = $this->follows()->pluck('id');

        return Tweet::whereIn('user_id', $friends)
            ->orWhere('user_id', $this->id)
            ->latest()->get();
    }

    public function tweets()
    {
        return $this->hasMany(Tweet::class)->latest();
    }

    public function getRouteKeyName()
    {
        return 'name';
    }

    public function path($apend = '')
    {
        $path = route('profile', $this->name);

        return $apend ? "{$path}/{$apend}" : $path;
    }


}

app/helpers.php
<?php

function current_user()
{
    return auth()->user();
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FollowsController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class FollowsController extends Controller
{
    public function store(User $user)
    {
        auth()->user()->toggleFollow($user);
        return back();
    }
}

app/Http/Controllers/ProfilesController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class ProfilesController extends Controller
{
    public function show(User $user)
    {
        return view('profiles.show', compact('user'));
    }

    public function edit(User $user)
    {
        $this->authorize('edit', $user);

        return view('profiles.edit', compact('user'));
    }
}

app/Http/Controllers/TweetsController.php
<?php

namespace App\Http\Controllers;

use App\Tweet;
use Illuminate\Http\Request;

class TweetsController extends Controller
{
    public function index()
    {
        return view('tweets.index', [
            'tweets' => auth()->user()->timeline()
        ]);
    }

    public function store()
    {
        $attributes = request()->validate(['body' => 'required|max:255']);

        Tweet::create([
            'user_id' => auth()->id(),
            'body' => $attributes['body']
        ]);

        return redirect()->route('home');
    }
}

resources/views/_friends-list.blade.php
<h3 class="font-bold text-xl mb-4">Following</h3>
<ul>
    @foreach(auth()->user()->follows as $user)
        <li>
            <div class="flex items-center text-sm">
                <a href="{{ route('profile', $user) }}" class="flex items-center text-sm">
                    <img
                        class="w-10 rounded-full mr-2 my-2"
                        src="{{ $user->avatar }}"
                        alt=""
                    >
                    {{ $user->name }}
                </a>
            </div>
        </li>
    @endforeach
</ul>

resources/views/_publish-tweet-panel.blade.php
<div class="border border-blue-400 rounded-lg py-4 px-8 mb-6">
    <form method="post" action="/tweets">
        @csrf
            <textarea
                name="body"
                class="w-full"
                placeholder="What's up doc?"
            ></textarea>

        <hr class="my-4">

        <footer class="flex justify-between">
            <img
                class="w-10 rounded-full mr-2"
                src="{{ auth()->user()->avatar }}"
                alt="Your avatar"
            >

            <button
                class="bg-blue-500 rounded-lg shadow py-2 px-2 text-white"
                type="submit"
            >
                Publish
            </button>
        </footer>
    </form>

    @error('body')
        <p class="text-red-500 text-sm mt-2">{{ $message }}</p>
    @enderror
</div>

resources/views/_sidebar-links.blade.php
<ul>
    <li>
        <a class="font-bold text-lg mb-4 block" href="{{ route('home') }}">
            Home
        </a>
    </li>
    <li>
        <a class="font-bold text-lg mb-4 block" href="/explore">
            Explore
        </a>
    </li>
    <li>
        <a class="font-bold text-lg mb-4 block" href="/notifications">
            Notifications
        </a>
    </li>
    <li>
        <a class="font-bold text-lg mb-4 block" href="/messages">
            Messages
        </a>
    </li>
    <li>
        <a class="font-bold text-lg mb-4 block" href="/bookmarks">
            Bookmarks
        </a>
    </li>
    <li>
        <a class="font-bold text-lg mb-4 block" href="/lists">
            Lists
        </a>
    </li>
    <li>
        <a class="font-bold text-lg mb-4 block" href="{{ route('profile', auth()->user()) }}">
            Profile
        </a>
    </li>
    <li>
        <a class="font-bold text-lg mb-4 block" href="/more">
            More
        </a>
    </li>
</ul>

resources/views/_timeline.blade.php
<div class="border border-gray-300 rounded-lg">

    @foreach($tweets as $tweet)

        @include('_tweet')

    @endforeach

</div>

resources/views/_tweet.blade.php
<div class="flex p-4 {{ $loop->last ? '' : 'border-b border-b-gray-400' }} ">
    <div class="flex-shrink-0 mr-4">
        <a href="{{ route('profile', $tweet->user->path()) }}">
            <img
                class="w-12 rounded-full mr-2"
                src="{{ $tweet->user->avatar }}"
                alt=""
            >
        </a>
    </div>

    <div>
        <h5 class="font-bold mb-4">
            <a href="{{ $tweet->user->path() }}">
                {{ $tweet->user->name }}
            </a>
        </h5>
        <p class="text-sm">
            {{ $tweet->body }}
        </p>
    </div>
</div>

resources/views/profiles/edit.blade.php
@extends('components.app')

@section('content')

@endsection

resources/views/profiles/show.blade.php
@extends('components.app')

@section('content')
    <header class="mb-6 relative" style="position: relative">
        <div class="relative">
            <img
                src="/images/default-profile-banner.png"
                class="rounded-lg mb-2"
                alt="Profile Banner"
            >

            <img
                class="w-32 rounded-full absolute bottom-0 transform -translate-x-1/2 translate-y-1/2"
                style="left: 50%"
                src="{{ $user->avatar }}"
                alt=""
                width="136"
            >
        </div>

        <div class="flex justify-between items-center mb-4">
            <div>
                <h2 class="font-bold text-2xl mb-0">{{ $user->name }}</h2>
                <p class="text-sm">Joined {{ $user->created_at->diffForHumans() }}</p>
            </div>

            <div class="flex">
                @can('edit', $user)
                    <a
                        href="{{ $user->path('edit') }}"
                        class="rounded-full border border-gray-300 py-2 px-4 mr-2 text-black text-xs"
                    >
                        Edit Profile
                    </a>
                @endcan

                @include('components.follow-button')

            </div>
        </div>

        <p class="text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan nisl eu sem lobortis pharetra. Fusce iaculis feugiat turpis, ac congue nunc porttitor nec. Nullam rutrum justo libero, vitae interdum ipsum posuere sed.</p>

    </header>

    @include('_timeline', [
        'tweets' => $user->tweets
    ])
@endsection

resources/views/tweets/index.blade.php
@extends('components.app')

@section('content')
    @include('_publish-tweet-panel')

    @include('_timeline')
@endsection